# Generated by Django 3.1.3 on 2020-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItensMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemPort', models.CharField(max_length=100)),
                ('itemIng', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Pizza', 'Pizza'), ('Sobremesas', 'Sobremesas'), ('Com alcool', 'Com alcool'), ('Sem alcool', 'Sem alcool')], max_length=40)),
                ('subcategoria', models.CharField(choices=[('Agua', 'Agua'), ('Cerveja', 'Cerveja'), ('Whisky', 'Whisky')], max_length=40)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
                ('ordem', models.DecimalField(choices=[('Calabresas', 0.2), ('Vegetariana', 0.4), ('Bolos', 0.6), ('Agua', 2.0), ('Capuccino', 2.1), ('Cerveja', 2.3), ('Whisky', 2.5)], decimal_places=2, max_digits=4)),
            ],
        ),
    ]
