# Generated by Django 3.1.3 on 2020-12-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintagecorner', '0002_auto_20201202_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensmenu',
            name='ordem',
            field=models.DecimalField(choices=[(0.2, 'Carne'), (0.4, 'Vegetariana'), (0.6, 'Bolos'), (2.0, 'Agua'), (2.1, 'Cafe'), (2.3, 'Cerveja'), (2.5, 'Whisky')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='itensmenu',
            name='subcategoria',
            field=models.CharField(choices=[('Carne', 'Carne'), ('Vegetariana', 'Vegetariana'), ('Bolos', 'Bolos'), ('Cafe', 'Cafe'), ('Agua', 'Agua'), ('Cerveja', 'Cerveja'), ('Whisky', 'Whisky')], max_length=40),
        ),
        migrations.AlterField(
            model_name='itensmenu',
            name='tipo',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Bebida', 'Bebida')], max_length=100),
        ),
    ]
