# Generated by Django 3.1.3 on 2020-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintagecorner', '0003_auto_20201202_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensmenu',
            name='ordem',
            field=models.DecimalField(choices=[(1.2, 'Carne'), (1.4, 'Vegetariana'), (1.6, 'Bolos'), (3.0, 'Agua'), (3.1, 'Cafe'), (3.3, 'Cerveja'), (3.5, 'Whisky')], decimal_places=2, max_digits=4),
        ),
    ]
