# Generated by Django 3.1.3 on 2020-12-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vintagecorner', '0006_auto_20201202_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nr_cadeiras', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='itensmenu',
            name='categoria',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Sobremesas', 'Sobremesas'), ('Com alcool', 'Com alcool'), ('Quentes', 'Quentes')], max_length=40),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='vintagecorner.itensmenu')),
                ('mesa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='vintagecorner.mesa')),
            ],
        ),
    ]
