# Generated by Django 3.1.3 on 2020-12-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintagecorner', '0008_pedido_totalitens'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
