# Generated by Django 3.1.3 on 2020-12-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintagecorner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensmenu',
            name='ordem',
            field=models.DecimalField(choices=[(0.2, 'Calabresas'), (0.4, 'Vegetariana'), (0.6, 'Bolos'), (2.0, 'Agua'), (2.1, 'Capuccino'), (2.3, 'Cerveja'), (2.5, 'Whisky')], decimal_places=2, max_digits=4),
        ),
    ]
