# Generated by Django 3.1.3 on 2020-12-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintagecorner', '0007_auto_20201202_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='totalItens',
            field=models.IntegerField(default=0),
        ),
    ]
